Streams
Vadifire/tweeting pull request #11
Opened 2019-05-16 20:41 UTC by Vadifire

2019-05-16 21:32 UTC, andrewcchau commented on src/main/java/tweeting/resources/FilterHomeTimelineResource.java
> +                        .collect(Collectors.toList());
Is this the cleanest way to do it?

2019-05-16 21:32 UTC, andrewcchau commented on src/main/java/tweeting/resources/FilterHomeTimelineResource.java
> +            "home timeline. ";
Check your resulting string

2019-05-17 19:50 UTC, kev-chan requested changes
keep looking at what you were looking at earlier, you haven't found the right thing yet.

2019-05-17 19:50 UTC, kev-chan commented on src/main/java/tweeting/resources/TweetResource.java
> +    public Response postTweet(@FormParam("message") Optional<String> message) {
you don't need optionals for the param

2019-05-20 18:21 UTC, kev-chan requested changes

2019-05-20 18:21 UTC, kev-chan commented on src/main/java/tweeting/models/Tweet.java
> +    public Optional<String> getMessage() {
you don't need optionals in the java objects

2019-05-20 18:21 UTC, kev-chan commented on src/main/java/tweeting/services/TwitterService.java
> +            logger.info("Successfully retrieved home timeline from Twitter.");
stream syntax here

2019-05-20 18:21 UTC, kev-chan commented on src/main/java/tweeting/services/TwitterService.java
> +    public Optional<Tweet> postTweet(String message) throws TwitterServiceResponseException,
same as above

2019-05-20 18:21 UTC, kev-chan commented on src/main/java/tweeting/resources/FilterHomeTimelineResource.java
> +    public Response getHomeTimeline(@QueryParam(FILTER_PARAM) String keyword) {
how re-usable is this?

2019-05-21 18:51 UTC, kev-chan requested changes

2019-05-21 18:51 UTC, kev-chan commented on src/main/java/tweeting/resources/FilterHomeTimelineResource.java
> +    public Response getHomeTimeline(@QueryParam(FILTER_PARAM) Optional<String> keyword) {
was this just copy and pasted?

2019-05-21 18:51 UTC, kev-chan commented on src/main/java/tweeting/resources/FilterHomeTimelineResource.java
> +    public Response getHomeTimeline(@QueryParam("keyword") String keyword) {
was this just copy and pasted?

2019-05-21 18:51 UTC, kev-chan commented on src/main/java/tweeting/services/TwitterService.java
> +        if (keyword == null) {
does this cover all of the cases?

2019-05-21 18:51 UTC, kev-chan commented on src/main/java/tweeting/services/TwitterService.java
> +        return Optional.of(statuses.stream()
are all of these lines necessary?

2019-05-21 21:40 UTC, kev-chan requested changes

2019-05-21 21:40 UTC, kev-chan commented on src/main/java/tweeting/resources/FilterHomeTimelineResource.java
> +                        .filter(t -> t.getMessage().isPresent())
what is this filter for?

2019-05-21 21:40 UTC, kev-chan commented on src/main/java/tweeting/resources/TwitterResource.java
> +                    .orElseThrow(() -> new NullPointerException("Twitter failed to respond with home timeline."));
this feels odd to just throw it below, if this is the case, why not just have the other class throw the exception?

2019-05-21 23:20 UTC, merged