Dependency Injection
Vadifire/tweeting pull request #12
Opened 2019-05-22 20:12 UTC by Vadifire

In addition to the Service->Resource dependency injection, I also used Dagger 2 to inject Twitter4J's Twitter API into my Twitter4JService class. I'm not sure if this was required, but it seemed in spirit of the DI goals defined here: [https://en.wikipedia.org/wiki/Dependency_injection#Intent](url) as it further decouples configuration.

2019-05-22 22:32 UTC, andrewcchau commented on src/main/java/tweeting/services/Twitter4JService.java
> +        Tweet tweet = new Tweet();
final

2019-05-22 22:32 UTC, andrewcchau commented on src/main/java/tweeting/services/Twitter4JService.java
> +            TwitterServiceCallException {
Keep exceptions on the same line

2019-05-22 22:32 UTC, andrewcchau commented on src/main/java/tweeting/services/Twitter4JService.java
> +            TwitterServiceCallException {
keep exceptions on the same line

2019-05-22 22:32 UTC, andrewcchau commented on src/main/java/tweeting/services/Twitter4JService.java
> +            TwitterUser user = new TwitterUser();
final

2019-05-22 22:32 UTC, andrewcchau commented on src/test/java/tweeting/resources/TwitterResourceTest.java
>      TwitterService service;
private

2019-05-23 16:42 UTC, kev-chan requested changes

2019-05-23 16:42 UTC, kev-chan commented on src/main/java/tweeting/injection/modules/TweetingModule.java
> +    static TwitterOAuthCredentials provideTwitterAuthentication(TweetingConfiguration conf) {
why the need for this and provideTwitterAPI in the other module class?

2019-05-23 16:42 UTC, kev-chan commented on src/test/java/tweeting/services/TwitterServiceTest.java
>  public class TwitterServiceTest {
why is this class called TwitterServiceTest?

2019-05-23 19:12 UTC, kev-chan commented on src/main/java/tweeting/injection/modules/Twitter4JModule.java
> +        final TwitterOAuthCredentials auth = conf.getTwitterAuthorization();
add null check, also, this likely does not need to be static method

2019-05-24 19:36 UTC, merged