Redo attempt at layers
Vadifire/tweeting pull request #9
Opened 2019-05-13 20:27 UTC by Vadifire

2019-05-13 21:33 UTC, andrewcchau requested changes

2019-05-13 21:33 UTC, andrewcchau commented on src/main/java/tweeting/TweetingApplication.java
> +            TwitterService service = TwitterService.getInstance();
Since you're using finals, make this final too

2019-05-13 21:33 UTC, andrewcchau commented on src/main/java/tweeting/resources/GetTimelineResource.java
>                          "Sending 500 Internal Server Error.");
Is it necessary to know the error code?

2019-05-13 21:33 UTC, andrewcchau commented on src/main/java/tweeting/resources/GetTimelineResource.java
> +            List<Status> statuses = service.getTweets();
final

2019-05-13 21:33 UTC, andrewcchau commented on src/main/java/tweeting/resources/PostTweetResource.java
> +            Status returnedStatus = service.postTweet(message); // Status should be updated to message
final

2019-05-13 21:33 UTC, andrewcchau commented on src/main/java/tweeting/services/TwitterService.java
> +    }
Is it necessary to re-set the API at any point for a service class?

2019-05-14 22:29 UTC, kev-chan requested changes

2019-05-14 22:29 UTC, kev-chan commented on src/main/java/tweeting/services/TwitterService.java
> +            TwitterServiceException e = new TwitterServiceException("Message parameter is blank.",
instead of error codes, it would be more straightforward to use different exceptions. One for unknown exceptions and one for other exceptions.

2019-05-14 22:29 UTC, kev-chan commented on src/test/java/tweeting/resources/GetTimelineResourceTest.java
> +        TwitterServiceException dummyException = mock(TwitterServiceException.class);
instead of mocking this, just create an instance

2019-05-15 21:23 UTC, merged